const types = {
  SET_NAVTITLE: "SET_NAVTITLE",
  //balance
  HIDE_CTRL: 'HIDE_CTRL',
  TOGGLE_CTRL: 'TOGGLE_CTRL',
  CHANGE_ACTIVE_TAB: 'CHANGE_ACTIVE_TAB',

  //user
  OAUTH: 'OAUTH',
  OAUTH_SUCCESS: 'OAUTH_SUCCESS',
  CHECK_IS_SIGNIN: 'CHECK_IS_SIGNIN',
  LOGIN: 'LOGIN',
  MOBILE_LOGIN: 'MOBILE_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  REGISTER: 'REGISTER',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_MOBILE: 'REGISTER_MOBILE',
  LOGOUT: 'LOGOUT',
  UPDATE_USER: 'UPDATE_USER',
  SET_TOKEN: 'SET_TOKEN',
  SET_TELAREA: 'SET_TELAREA',
  SET_MOBILELOGIN: 'SET_MOBILELOGIN',
  USER_HEART_BEAT: 'USER_HEART_BEAT',
  //user sider
  CHANGE_REFFER: 'CHANGE_REFFER',
  HANLDER_USER_SIDER: 'HANLDER_USER_SIDER',
  SET_WITHDRAW_INFO: 'SET_WITHDRAW_INFO',
  SET_WITHDRAW_STATUS: 'SET_WITHDRAW_STATUS',

  //glogal
  POLY_TRANSFER: 'POLY_TRANSFER',
  //notice
  GET_NEW_NOTICE: 'GET_NEW_NOTICE',
  GET_NEW_NOTICE_SUCCESS: 'GET_NEW_NOTICE_SUCCESS',
  GET_GLOBAL_ACTIVITY: 'GET_GLOBAL_ACTIVITY',
  GET_GLOBAL_ACTIVITY_SUCCESS: 'GET_GLOBAL_ACTIVITY_SUCCESS',
  CLOSE_GLOBAL_ACTIVITY: 'CLOSE_GLOBAL_ACTIVITY',

  GET_GLOBAL_ANNOUNCEMENT: 'GET_GLOBAL_ANNOUNCEMENT',
  GET_GLOBAL_ANNOUNCEMENT_SUCCESS: 'GET_GLOBAL_ANNOUNCEMENT_SUCCESS',

  GET_GLOBAL_ANNOUNCEMENT_UNREAD: 'GET_GLOBAL_ANNOUNCEMENT_UNREAD',
  GET_GLOBAL_ANNOUNCEMENT_UNREAD_SUCCESS: 'GET_GLOBAL_ANNOUNCEMENT_UNREAD_SUCCESS',


  CLOSE_TODAY_NOTICE: 'CLOSE_TODAY_NOTICE',
  CLEAR_NOTICE: 'CLEAR_NOTICE',
  //game
  GET_MAINTAIN_STATUS: 'GET_MAINTAIN_STATUS',
  GET_MAINTAIN_STATUS_SUCCESS: 'GET_MAINTAIN_STATUS_SUCCESS',
  GET_SECURITY: 'GET_SECURITY',
  GET_SECURITY_SUCCESS: 'GET_SECURITY_SUCCESS',

  //sports
  GET_TODAY_LIVE: 'GET_TODAY_LIVE',
  GET_TODAY_LIVE_SUCCESS: 'GET_TODAY_LIVE_SUCCESS',
  GET_LINE_UP: 'GET_LINE_UP',
  GET_LINE_UP_SUCCESS: 'GET_LINE_UP_SUCCESS',
  SET_MATCH_ID: 'SET_MATCH_ID',
  GET_INJURY: 'GET_INJURY',
  GET_INJURY_SUCCESS: 'GET_INJURY_SUCCESS',
  GET_SPORTS: 'GET_SPORTS',
  GET_SPORTS_LIVE: 'GET_SPORTS_LIVE',
  GET_SPORTS_LIVE_SUCCESS: 'GET_SPORTS_LIVE_SUCCESS',
  GET_SPORTS_VIDEO: 'GET_SPORTS_VIDEO',
  GET_SPORTS_VIDEO_SUCCESS: 'GET_SPORTS_VIDEO_SUCCESS',
  SET_SPORTS_TYPE: 'SET_SPORTS_TYPE',





  GET_ANALYSIS: 'GET_ANALYSIS',
  GET_ANALYSIS_SUCCESS: 'GET_ANALYSIS_SUCCESS',
  GET_FOOTBALL_SCSG: 'GET_FOOTBALL_SCSG',
  GET_FOOTBALL_SCSG_SUCCESS: 'GET_FOOTBALL_SCSG_SUCCESS',
  GET_BASKETBALL_SCSG: 'GET_BASKETBALL_SCSG',
  GET_BASKETBALL_SCSG_SUCCESS: 'GET_BASKETBALL_SCSG_SUCCESS',
  GET_FOOTBALL_MATCH_LIST: 'GET_FOOTBALL_MATCH_LIST',
  GET_BASKETBALL_MATCH_LIST: 'GET_BASKETBALL_MATCH_LIST',

  SPORTS_DATA_FILTER: 'SPORTS_DATA_FILTER',
  COMPUTED_SPORTS_VIDEO: 'COMPUTED_SPORTS_VIDEO',
  UNION_SPORTS_DATA: 'UNION_SPORTS_DATA',
  SPORTS_DATA_CHANGE: 'SPORTS_DATA_CHANGE',

  GET_BALANCE: 'GET_BALANCE',
  GET_ALL_BALANCE: 'GET_ALL_BALANCE',
  TRANSFER_IN_CHANNEL: 'TRANSFER_IN',
  TRANSFER_IN_CHANNEL_SUCCESS: 'TRANSFER_IN_CHANNEL_SUCCESS',
  TRANSFER_TO: 'TRANSFER_TO',
  TRANSFER_TO_SUCCESS: 'TRANSFER_TO_SUCCESS',
  GET_BALANCE_STATUS: 'GET_BALANCE_STATUS',
  GET_BALANCE_STATUS_SUCCESS: 'GET_BALANCE_STATUS_SUCCESS',
  GET_BALANCE_SUCCESS: 'GET_BALANCE_SUCCESS',
  //popup
  RIGHT_FILTER_VISIBILITY: 'RIGHT_FILTER_VISIBILITY',
  START_RED_PACKET: 'START_RED_PACKET',
  START_RED_QUA: 'START_RED_QUA',
};

export default types;
